[build]
target = ["x86_64-unknown-linux-musl", "x86_64-unknown-linux-gnu", "i686-unknown-linux-gnu"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "linker-flavor=ld.lld"]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker-flavor=ld.lld"]
[target.i686-unknown-linux-gnu]
rustflags = ["-C", "linker-flavor=ld.lld"]



# debian 11: x86_64-unknown-linux-gnu

# 
# [build]
# target = ["x86_64-unknown-linux-gnu"]
# 
# [target.x86_64-unknown-linux-gnu]
# linker = "rust-lld"
# 

# rustup target list
# rustup target add i686-linux-gnu-gcc
# cargo build --release --config ./.cargo/config.toml