[package]
name = "hook-tests"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["windef", "winuser"] }

[build-dependencies]
cc = "1.0"
[dependencies]
lazy_static = "1.5.0"